# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founderID', models.CharField(max_length=50)),
                ('numberOfMembers', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(to='login.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleID', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('numberOfLateness', models.IntegerField(default=0)),
                ('numberOfAbsence', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
