# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20180808_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='defaultImage.jpg', upload_to=''),
        ),
    ]
