# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 22:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20180809_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='settings.MEDIA_ROOT/defaultImage.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Administrator\\Documents\\Project\\TOMAK\\KimChongMu\\website\\club\\media'), upload_to=''),
        ),
    ]
