# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default='0:0'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default='2018-01-01'),
        ),
    ]
