# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20180806_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
