# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20180806_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='accept',
            field=models.NullBooleanField(),
        ),
    ]
