# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20180806_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Meeting'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
        ),
    ]
