# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20180806_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
