# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20180807_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='checkCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
