# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('authority', models.IntegerField(blank=True, max_length=8, null=True)),
                ('attendance', models.IntegerField(blank=True, max_length=16, null=True)),
                ('pwd', models.CharField(blank=True, max_length=32, null=True)),
                ('attendance_time', models.DateTimeField(blank=True, max_length=16, null=True, verbose_name='date published')),
            ],
            options={
                'db_table': 'Member',
                'managed': False,
            },
        ),
    ]
