# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founderID', models.CharField(max_length=50)),
                ('numberOfMembers', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('authority', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleID', models.CharField(max_length=50)),
                ('startTime', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('late', models.IntegerField(default=0)),
                ('numberOfLateness', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('numberOfabsence', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to='manager.Member'),
        ),
    ]
