# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='absent',
            new_name='numberOfAbsence',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='late',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='numberOfabsence',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='rule',
            name='ruleID',
            field=models.IntegerField(default=0),
        ),
    ]
